
# Checkout the documentation for this YAML template here:
# https://github.com/keesschollaart81/AzureCostInsights.Marketplace/wiki/YAML-Pipeline

trigger: none
pr: none

jobs:
- job: "Azure_Cost_Insights"
  timeoutInMinutes: 120  
  pool: "Hosted Ubuntu 1604"

  steps:
  
  - task: keesschollaart.AzureCostInsights-Dev.AzureCostInsightsWidget.DownloadTask.DownloadCostData@1
    displayName: 'Download cost data - Kees Prive'
    inputs:
      ConnectedServiceNameARM: '86af7676-6a6f-4ae1-9fea-538d6b69d1ca' 
      apiToUse: usage
      currency: EUR
      locale: 'nl-nl'
      regioInfo: NL 

  - task: keesschollaart.AzureCostInsights-Dev.AzureCostInsightsWidget.DownloadTask.DownloadCostData@1
    displayName: 'Download Cost Data'
    inputs:
      ConnectedServiceNameARM: 'e5834a49-9dd8-4dc1-8dda-df2d20501da0'
  
  - task: keesschollaart.AzureCostInsights-Dev.AzureCostInsightsWidget.PublishTask.PublishCostData@1
    displayName: 'Publish Cost Data'
    continueOnError: true