# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#  branches:
#    include:
#    - main

stages:
- stage: First_Stage
  jobs:
  - job: Job1
    pool:
      vmImage: windows-latest
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
      
            echo 'My First Stage'

- stage: Second_Stage
  jobs:
  - job: Job2
#Please, change the agent pool using the Hosted Agent instead of the Microsoft VMImage
    pool:
      vmImage: Ubuntu-latest
    steps:
     - task: Bash@3
       inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
      
            echo 'My Second Stage'

#Examples:

#EX1
#condition: and(succeeded(), eq(variables['BuildWebApp2'], 'true'))

#EX2
#- job: Job2
#  dependsOn: Job1
#  condition: failed() # this job will only run if Foo fails